name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@main
        with:
          dotnet-version: 5.0.*

      # - name: restore
      #   run: dotnet restore

      # - name: build
      #   run: dotnet build --no-restore -c Release

      # - name: tset
      #   run: dotnet test --no-restore -c Release
